import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { ListingWithScore, SearchAggregations, SearchFilters } from '@/lib/types';

// ── Static JSON fallback for serverless environments ────────────────────
//
// When the DB is empty/error, we fall back to a pre-built JSON snapshot.
// The snapshot is generated by scripts/export-listings-to-json.py
// and committed to the repo at data/letgo-listings.json.

export interface FallbackListing extends ListingWithScore {
  priceHistory: Array<{ id: string; price: number; recordedAt: string }>;
}

let cachedFallback: FallbackListing[] | null = null;

export function loadFallbackListings(): FallbackListing[] {
  if (cachedFallback !== null) return cachedFallback;

  try {
    const filePath = join(process.cwd(), 'data', 'letgo-listings.json');
    const raw = readFileSync(filePath, 'utf-8');
    const parsed = JSON.parse(raw) as FallbackListing[];
    cachedFallback = Array.isArray(parsed) ? parsed : [];
    return cachedFallback;
  } catch (err) {
    console.warn('[fallback] Could not load data/letgo-listings.json:', (err as Error).message);
    cachedFallback = [];
    return cachedFallback;
  }
}

function filterFallback(listings: FallbackListing[], filters: SearchFilters): FallbackListing[] {
  return listings.filter((l) => {
    if (filters.make && l.make !== filters.make) return false;
    if (filters.model && l.model !== filters.model) return false;
    if (filters.yearMin && l.year < filters.yearMin) return false;
    if (filters.yearMax && l.year > filters.yearMax) return false;
    if (filters.priceMin && l.price < filters.priceMin) return false;
    if (filters.priceMax && l.price > filters.priceMax) return false;
    if (filters.mileageMax && (l.mileageKm ?? Infinity) > filters.mileageMax) return false;
    if (filters.fuelType && l.fuelType !== filters.fuelType) return false;
    if (filters.transmission && l.transmission !== filters.transmission) return false;
    if (filters.bodyType && l.bodyType !== filters.bodyType) return false;
    if (filters.city && l.city !== filters.city) return false;
    if (filters.sellerType && l.sellerType !== filters.sellerType) return false;
    if (filters.dealTag && l.dealTag !== filters.dealTag) return false;
    return true;
  });
}

function sortFallback(listings: FallbackListing[], sortBy?: string | null): FallbackListing[] {
  const sorted = [...listings];
  switch (sortBy) {
    case 'price_asc': return sorted.sort((a, b) => a.price - b.price);
    case 'price_desc': return sorted.sort((a, b) => b.price - a.price);
    case 'year_desc': return sorted.sort((a, b) => b.year - a.year);
    case 'year_asc': return sorted.sort((a, b) => a.year - b.year);
    case 'mileage_asc': return sorted.sort((a, b) => (a.mileageKm ?? Infinity) - (b.mileageKm ?? Infinity));
    case 'deal_score_desc': return sorted.sort((a, b) => (b.dealScore ?? -Infinity) - (a.dealScore ?? -Infinity));
    case 'newest':
    default: return sorted.sort((a, b) => new Date(b.lastSeenAt).getTime() - new Date(a.lastSeenAt).getTime());
  }
}

function buildFallbackAggregations(listings: FallbackListing[]): SearchAggregations {
  const makeMap = new Map<string, number>();
  const cityMap = new Map<string, number>();
  const fuelTypeMap = new Map<string, number>();
  const transmissionMap = new Map<string, number>();
  const bodyTypeMap = new Map<string, number>();
  const dealTagMap = new Map<string, number>();

  let minPrice = Infinity, maxPrice = -Infinity, minYear = Infinity, maxYear = -Infinity;

  for (const item of listings) {
    if (item.make) makeMap.set(item.make, (makeMap.get(item.make) || 0) + 1);
    if (item.city) cityMap.set(item.city, (cityMap.get(item.city) || 0) + 1);
    if (item.fuelType) fuelTypeMap.set(item.fuelType, (fuelTypeMap.get(item.fuelType) || 0) + 1);
    if (item.transmission) transmissionMap.set(item.transmission, (transmissionMap.get(item.transmission) || 0) + 1);
    if (item.bodyType) bodyTypeMap.set(item.bodyType, (bodyTypeMap.get(item.bodyType) || 0) + 1);
    if (item.dealTag) dealTagMap.set(item.dealTag, (dealTagMap.get(item.dealTag) || 0) + 1);
    if (item.price < minPrice) minPrice = item.price;
    if (item.price > maxPrice) maxPrice = item.price;
    if (item.year < minYear) minYear = item.year;
    if (item.year > maxYear) maxYear = item.year;
  }

  const toArr = (m: Map<string, number>) =>
    Array.from(m.entries()).map(([name, count]) => ({ name, count })).sort((a, b) => b.count - a.count);

  return {
    makes: toArr(makeMap), cities: toArr(cityMap),
    fuelTypes: toArr(fuelTypeMap), transmissions: toArr(transmissionMap),
    bodyTypes: toArr(bodyTypeMap),
    priceRange: { min: listings.length ? minPrice : 0, max: listings.length ? maxPrice : 0 },
    yearRange: { min: listings.length ? minYear : 0, max: listings.length ? maxYear : 0 },
    totalActive: listings.length,
    dealBreakdown: Array.from(dealTagMap.entries()).map(([tag, count]) => ({ tag, count })).sort((a, b) => b.count - a.count),
  };
}

export function queryFallbackListings(filters: SearchFilters): {
  listings: FallbackListing[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
  aggregations: SearchAggregations;
} {
  const all = loadFallbackListings();
  const filtered = filterFallback(all, filters);
  const sorted = sortFallback(filtered, filters.sortBy);

  const page = Math.max(1, filters.page || 1);
  const limit = Math.min(100, Math.max(1, filters.limit || 20));
  const skip = (page - 1) * limit;
  const paged = sorted.slice(skip, skip + limit);

  const aggregations = buildFallbackAggregations(filtered);

  return {
    listings: paged, total: sorted.length, page, limit,
    totalPages: Math.ceil(sorted.length / limit), aggregations,
  };
}
